// Points for a full Grand Prix (P1..P10). Index = finishing position.
// P0 is dummy, P1=25, P2=18, etc.
export const RACE_POINTS = [0, 25, 18, 15, 12, 10, 8, 6, 4, 2, 1];

// Base driver data
// Note: We might want to flag the title contenders explicitly
export const BASE_DRIVERS = [
  {
    id: "norris",
    name: "L. Norris",
    team: "McLaren",
    country: "United Kingdom",
    points: 408,
    wins: 7,
    podiums: 17,
    isContender: true,
  },
  {
    id: "verstappen",
    name: "M. Verstappen",
    team: "Red Bull",
    country: "Netherlands",
    points: 396,
    wins: 7,
    podiums: 14,
    isContender: true,
  },
  {
    id: "piastri",
    name: "O. Piastri",
    team: "McLaren",
    country: "Australia",
    points: 392,
    wins: 7,
    podiums: 15,
    isContender: true,
  },
  {
    id: "russell",
    name: "G. Russell",
    team: "Mercedes",
    country: "United Kingdom",
    points: 309,
    wins: 2,
    podiums: 9,
    isContender: false,
  },
  {
    name: "C. Leclerc",
    team: "Ferrari",
    country: "Monaco",
    points: 230,
    wins: 0,
    podiums: 7,
  },
  {
    name: "L. Hamilton",
    team: "Ferrari",
    country: "United Kingdom",
    points: 152,
    wins: 0,
    podiums: 0,
  },
  {
    name: "A.K. Antonelli",
    team: "Mercedes",
    country: "Italy",
    points: 150,
    wins: 0,
    podiums: 3,
  },
  {
    name: "A. Albon",
    team: "Williams",
    country: "Thailand",
    points: 73,
    wins: 0,
    podiums: 0,
  },
  {
    name: "C. Sainz Jr.",
    team: "Williams",
    country: "Spain",
    points: 64,
    wins: 0,
    podiums: 2,
  },
  {
    name: "I. Hadjar",
    team: "RB",
    country: "France",
    points: 51,
    wins: 0,
    podiums: 1,
  },
  {
    name: "N. Hülkenberg",
    team: "Kick Sauber",
    country: "Germany",
    points: 49,
    wins: 0,
    podiums: 1,
  },
  {
    name: "F. Alonso",
    team: "Aston Martin",
    country: "Spain",
    points: 48,
    wins: 0,
    podiums: 0,
  },
  {
    name: "O. Bearman",
    team: "Haas",
    country: "United Kingdom",
    points: 41,
    wins: 0,
    podiums: 0,
  },
  {
    name: "L. Lawson",
    team: "RB",
    country: "New Zealand",
    points: 38,
    wins: 0,
    podiums: 0,
  },
  {
    name: "Y. Tsunoda",
    team: "Red Bull",
    country: "Japan",
    points: 33,
    wins: 0,
    podiums: 0,
  },
  {
    name: "E. Ocon",
    team: "Haas",
    country: "France",
    points: 32,
    wins: 0,
    podiums: 0,
  },
  {
    name: "L. Stroll",
    team: "Aston Martin",
    country: "Canada",
    points: 32,
    wins: 0,
    podiums: 0,
  },
  {
    name: "P. Gasly",
    team: "Alpine",
    country: "France",
    points: 22,
    wins: 0,
    podiums: 0,
  },
  {
    name: "G. Bortoleto",
    team: "Kick Sauber",
    country: "Brazil",
    points: 19,
    wins: 0,
    podiums: 0,
  },
  {
    name: "F. Colapinto",
    team: "Alpine",
    country: "Argentina",
    points: 0,
    wins: 0,
    podiums: 0,
  },
  {
    name: "J. Doohan",
    team: "Alpine",
    country: "Australia",
    points: 0,
    wins: 0,
    podiums: 0,
  },
];
